apiVersion: v1
kind: Service
metadata:
  name: bootdo
  namespace: {{ .Values.global.namespace }}
spec:
  ports:
  - name: http
    nodePort: 32080
    port: 8080
    protocol: TCP
    targetPort: 8080
  - name: https
    nodePort: 32089
    port: 8443
    protocol: TCP
    targetPort: 8443
  selector:
    app: bootdo
  sessionAffinity: None
  type: NodePort